In [44]:
!pip install pyspark

Requirement already satisfied: pyspark in /opt/conda/lib/python3.10/site-packages (3.5.3)
Requirement already satisfied: py4j==0.10.9.7 in /opt/conda/lib/python3.10/site-packages (from pyspark) (0.10.9.7)

In [45]:
from pyspark.sql import SparkSession

In [46]:
spark=SparkSession.builder.appName('Cruise').getOrCreate()

In [47]:
spark

In [48]:
# Read dataset
spark.read.option('header','true').csv('/kaggle/input/cruise-used-for-pyspark/cruise_dataset.csv',inferSchema=True)

DataFrame[Ship_name: string, Cruise_line: string, Age: int, Tonnage: double, passengers: double, length: double, cabins: double, passenger_density: double, crew: double]

In [49]:
df_cruise=spark.read.option('header','true').csv('/kaggle/input/cruise-used-for-pyspark/cruise_dataset.csv',inferSchema=True)

In [50]:
#Check the datatypes/Schemas
df_cruise.printSchema()

root
 |-- Ship_name: string (nullable = true)
 |-- Cruise_line: string (nullable = true)
 |-- Age: integer (nullable = true)
 |-- Tonnage: double (nullable = true)
 |-- passengers: double (nullable = true)
 |-- length: double (nullable = true)
 |-- cabins: double (nullable = true)
 |-- passenger_density: double (nullable = true)
 |-- crew: double (nullable = true)

In [51]:
type(df_cruise)

pyspark.sql.dataframe.DataFrame

In [52]:
df_cruise.columns

['Ship_name',
 'Cruise_line',
 'Age',
 'Tonnage',
 'passengers',
 'length',
 'cabins',
 'passenger_density',
 'crew']

In [53]:
df_cruise.head(3)

[Row(Ship_name='Journey', Cruise_line='Azamara', Age=6, Tonnage=30.276999999999997, passengers=6.94, length=5.94, cabins=3.55, passenger_density=42.64, crew=3.55),
 Row(Ship_name='Quest', Cruise_line='Azamara', Age=6, Tonnage=30.276999999999997, passengers=6.94, length=5.94, cabins=3.55, passenger_density=42.64, crew=3.55),
 Row(Ship_name='Celebration', Cruise_line='Carnival', Age=26, Tonnage=47.262, passengers=14.86, length=7.22, cabins=7.43, passenger_density=31.8, crew=6.7)]

In [54]:
df_cruise.show()

+-----------+-----------+---+------------------+----------+------+------+-----------------+----+
|  Ship_name|Cruise_line|Age|           Tonnage|passengers|length|cabins|passenger_density|crew|
+-----------+-----------+---+------------------+----------+------+------+-----------------+----+
|    Journey|    Azamara|  6|30.276999999999997|      6.94|  5.94|  3.55|            42.64|3.55|
|      Quest|    Azamara|  6|30.276999999999997|      6.94|  5.94|  3.55|            42.64|3.55|
|Celebration|   Carnival| 26|            47.262|     14.86|  7.22|  7.43|             31.8| 6.7|
|   Conquest|   Carnival| 11|             110.0|     29.74|  9.53| 14.88|            36.99|19.1|
|    Destiny|   Carnival| 17|           101.353|     26.42|  8.92| 13.21|            38.36|10.0|
|    Ecstasy|   Carnival| 22|            70.367|     20.52|  8.55|  10.2|            34.29| 9.2|
|    Elation|   Carnival| 15|            70.367|     20.52|  8.55|  10.2|            34.29| 9.2|
|    Fantasy|   Carnival| 23|            70.367|     20.56|  8.55| 10.22|            34.23| 9.2|
|Fascination|   Carnival| 19|            70.367|     20.52|  8.55|  10.2|            34.29| 9.2|
|    Freedom|   Carnival|  6|110.23899999999999|      37.0|  9.51| 14.87|            29.79|11.5|
|      Glory|   Carnival| 10|             110.0|     29.74|  9.51| 14.87|            36.99|11.6|
|    Holiday|   Carnival| 28|            46.052|     14.52|  7.27|  7.26|            31.72| 6.6|
|Imagination|   Carnival| 18|            70.367|     20.52|  8.55|  10.2|            34.29| 9.2|
|Inspiration|   Carnival| 17|            70.367|     20.52|  8.55|  10.2|            34.29| 9.2|
|     Legend|   Carnival| 11|              86.0|     21.24|  9.63| 10.62|            40.49| 9.3|
|   Liberty*|   Carnival|  8|             110.0|     29.74|  9.51| 14.87|            36.99|11.6|
|    Miracle|   Carnival|  9|              88.5|     21.24|  9.63| 10.62|            41.67|10.3|
|   Paradise|   Carnival| 15|            70.367|     20.52|  8.55|  10.2|            34.29| 9.2|
|      Pride|   Carnival| 12|              88.5|     21.24|  9.63| 11.62|            41.67| 9.3|
|  Sensation|   Carnival| 20|            70.367|     20.52|  8.55|  10.2|            34.29| 9.2|
+-----------+-----------+---+------------------+----------+------+------+-----------------+----+
only showing top 20 rows

In [55]:
#Selecting a columns
df_cruise.select('Ship_name')

DataFrame[Ship_name: string]

In [56]:
df_cruise.select('Ship_name').show()

+-----------+
|  Ship_name|
+-----------+
|    Journey|
|      Quest|
|Celebration|
|   Conquest|
|    Destiny|
|    Ecstasy|
|    Elation|
|    Fantasy|
|Fascination|
|    Freedom|
|      Glory|
|    Holiday|
|Imagination|
|Inspiration|
|     Legend|
|   Liberty*|
|    Miracle|
|   Paradise|
|      Pride|
|  Sensation|
+-----------+
only showing top 20 rows

In [57]:
df_cruise.select('Ship_name', 'Cruise_line').show()

+-----------+-----------+
|  Ship_name|Cruise_line|
+-----------+-----------+
|    Journey|    Azamara|
|      Quest|    Azamara|
|Celebration|   Carnival|
|   Conquest|   Carnival|
|    Destiny|   Carnival|
|    Ecstasy|   Carnival|
|    Elation|   Carnival|
|    Fantasy|   Carnival|
|Fascination|   Carnival|
|    Freedom|   Carnival|
|      Glory|   Carnival|
|    Holiday|   Carnival|
|Imagination|   Carnival|
|Inspiration|   Carnival|
|     Legend|   Carnival|
|   Liberty*|   Carnival|
|    Miracle|   Carnival|
|   Paradise|   Carnival|
|      Pride|   Carnival|
|  Sensation|   Carnival|
+-----------+-----------+
only showing top 20 rows

In [58]:
df_cruise.describe()

DataFrame[summary: string, Ship_name: string, Cruise_line: string, Age: string, Tonnage: string, passengers: string, length: string, cabins: string, passenger_density: string, crew: string]

In [59]:
df_cruise.describe().show()

+-------+---------+-----------+------------------+------------------+-----------------+-----------------+------------------+-----------------+-----------------+
|summary|Ship_name|Cruise_line|               Age|           Tonnage|       passengers|           length|            cabins|passenger_density|             crew|
+-------+---------+-----------+------------------+------------------+-----------------+-----------------+------------------+-----------------+-----------------+
|  count|      158|        158|               158|               158|              158|              158|               158|              158|              158|
|   mean| Infinity|       NULL|15.689873417721518| 71.28467088607599|18.45740506329114|8.130632911392404| 8.830000000000005|39.90094936708861|7.794177215189873|
| stddev|     NULL|       NULL| 7.615691058751413|37.229540025907866|9.677094775143416|1.793473548054825|4.4714172221480615| 8.63921711391542|3.503486564627034|
|    min|Adventure|    Azamara|                 4|             2.329|             0.66|             2.79|              0.33|             17.7|             0.59|
|    max|Zuiderdam|   Windstar|                48|             220.0|             54.0|            11.82|              27.0|            71.43|             21.0|
+-------+---------+-----------+------------------+------------------+-----------------+-----------------+------------------+-----------------+-----------------+

In [ ]:
#add Columns
# df_cruise.withColumn('New column', df_cruise['New column']+2).show()

In [60]:
#rename a column
df_cruise.withColumnRenamed('Ship_name','ship_name')

DataFrame[ship_name: string, Cruise_line: string, Age: int, Tonnage: double, passengers: double, length: double, cabins: double, passenger_density: double, crew: double]

In [ ]:
#drop columns
# df.drop('Column name')

In [61]:
# any==how
df_cruise.na.drop(how="any").show()

+-----------+-----------+---+------------------+----------+------+------+-----------------+----+
|  Ship_name|Cruise_line|Age|           Tonnage|passengers|length|cabins|passenger_density|crew|
+-----------+-----------+---+------------------+----------+------+------+-----------------+----+
|    Journey|    Azamara|  6|30.276999999999997|      6.94|  5.94|  3.55|            42.64|3.55|
|      Quest|    Azamara|  6|30.276999999999997|      6.94|  5.94|  3.55|            42.64|3.55|
|Celebration|   Carnival| 26|            47.262|     14.86|  7.22|  7.43|             31.8| 6.7|
|   Conquest|   Carnival| 11|             110.0|     29.74|  9.53| 14.88|            36.99|19.1|
|    Destiny|   Carnival| 17|           101.353|     26.42|  8.92| 13.21|            38.36|10.0|
|    Ecstasy|   Carnival| 22|            70.367|     20.52|  8.55|  10.2|            34.29| 9.2|
|    Elation|   Carnival| 15|            70.367|     20.52|  8.55|  10.2|            34.29| 9.2|
|    Fantasy|   Carnival| 23|            70.367|     20.56|  8.55| 10.22|            34.23| 9.2|
|Fascination|   Carnival| 19|            70.367|     20.52|  8.55|  10.2|            34.29| 9.2|
|    Freedom|   Carnival|  6|110.23899999999999|      37.0|  9.51| 14.87|            29.79|11.5|
|      Glory|   Carnival| 10|             110.0|     29.74|  9.51| 14.87|            36.99|11.6|
|    Holiday|   Carnival| 28|            46.052|     14.52|  7.27|  7.26|            31.72| 6.6|
|Imagination|   Carnival| 18|            70.367|     20.52|  8.55|  10.2|            34.29| 9.2|
|Inspiration|   Carnival| 17|            70.367|     20.52|  8.55|  10.2|            34.29| 9.2|
|     Legend|   Carnival| 11|              86.0|     21.24|  9.63| 10.62|            40.49| 9.3|
|   Liberty*|   Carnival|  8|             110.0|     29.74|  9.51| 14.87|            36.99|11.6|
|    Miracle|   Carnival|  9|              88.5|     21.24|  9.63| 10.62|            41.67|10.3|
|   Paradise|   Carnival| 15|            70.367|     20.52|  8.55|  10.2|            34.29| 9.2|
|      Pride|   Carnival| 12|              88.5|     21.24|  9.63| 11.62|            41.67| 9.3|
|  Sensation|   Carnival| 20|            70.367|     20.52|  8.55|  10.2|            34.29| 9.2|
+-----------+-----------+---+------------------+----------+------+------+-----------------+----+
only showing top 20 rows

In [62]:
#threshold = 2 will delete all rows with two non null vales
df_cruise.na.drop(how="any", thresh=2).show()

+-----------+-----------+---+------------------+----------+------+------+-----------------+----+
|  Ship_name|Cruise_line|Age|           Tonnage|passengers|length|cabins|passenger_density|crew|
+-----------+-----------+---+------------------+----------+------+------+-----------------+----+
|    Journey|    Azamara|  6|30.276999999999997|      6.94|  5.94|  3.55|            42.64|3.55|
|      Quest|    Azamara|  6|30.276999999999997|      6.94|  5.94|  3.55|            42.64|3.55|
|Celebration|   Carnival| 26|            47.262|     14.86|  7.22|  7.43|             31.8| 6.7|
|   Conquest|   Carnival| 11|             110.0|     29.74|  9.53| 14.88|            36.99|19.1|
|    Destiny|   Carnival| 17|           101.353|     26.42|  8.92| 13.21|            38.36|10.0|
|    Ecstasy|   Carnival| 22|            70.367|     20.52|  8.55|  10.2|            34.29| 9.2|
|    Elation|   Carnival| 15|            70.367|     20.52|  8.55|  10.2|            34.29| 9.2|
|    Fantasy|   Carnival| 23|            70.367|     20.56|  8.55| 10.22|            34.23| 9.2|
|Fascination|   Carnival| 19|            70.367|     20.52|  8.55|  10.2|            34.29| 9.2|
|    Freedom|   Carnival|  6|110.23899999999999|      37.0|  9.51| 14.87|            29.79|11.5|
|      Glory|   Carnival| 10|             110.0|     29.74|  9.51| 14.87|            36.99|11.6|
|    Holiday|   Carnival| 28|            46.052|     14.52|  7.27|  7.26|            31.72| 6.6|
|Imagination|   Carnival| 18|            70.367|     20.52|  8.55|  10.2|            34.29| 9.2|
|Inspiration|   Carnival| 17|            70.367|     20.52|  8.55|  10.2|            34.29| 9.2|
|     Legend|   Carnival| 11|              86.0|     21.24|  9.63| 10.62|            40.49| 9.3|
|   Liberty*|   Carnival|  8|             110.0|     29.74|  9.51| 14.87|            36.99|11.6|
|    Miracle|   Carnival|  9|              88.5|     21.24|  9.63| 10.62|            41.67|10.3|
|   Paradise|   Carnival| 15|            70.367|     20.52|  8.55|  10.2|            34.29| 9.2|
|      Pride|   Carnival| 12|              88.5|     21.24|  9.63| 11.62|            41.67| 9.3|
|  Sensation|   Carnival| 20|            70.367|     20.52|  8.55|  10.2|            34.29| 9.2|
+-----------+-----------+---+------------------+----------+------+------+-----------------+----+
only showing top 20 rows

In [ ]:
#subset
#df_cruise.na.drop(how="any", subset = ['Ship_name']).show()

In [ ]:
# filling the missing values
#df_cruise.na.fill('Missinisnull().sum()
this data set has no Missing values

In [20]:
# filling Missing values with mean with new values in new columns
from pyspark.ml.feature import Imputer

#imputer = Imputer(
 #   inputCols=['Col1', 'Col2', 'Col3'],
 #   outputCols=["{}_imputed".format(c) for c in ['Col1', 'Col2', 'Col3']]
 #   ).setStrategy("mean")

In [22]:
#add imputed columns to df
#imputer.fit(df_cruise)._transform(df_cruise).show()

In [63]:
#Filter operations
df_cruise.filter("Tonnage>50").select(['Ship_name']).show()

+-----------+
|  Ship_name|
+-----------+
|   Conquest|
|    Destiny|
|    Ecstasy|
|    Elation|
|    Fantasy|
|Fascination|
|    Freedom|
|      Glory|
|Imagination|
|Inspiration|
|     Legend|
|   Liberty*|
|    Miracle|
|   Paradise|
|      Pride|
|  Sensation|
|     Spirit|
|    Triumph|
|      Valor|
|    Victory|
+-----------+
only showing top 20 rows

In [64]:
#groupby
df_cruise.groupBy('Age').sum().show()

+---+--------+------------------+------------------+------------------+------------------+----------------------+------------------+
|Age|sum(Age)|      sum(Tonnage)|   sum(passengers)|       sum(length)|       sum(cabins)|sum(passenger_density)|         sum(crew)|
+---+--------+------------------+------------------+------------------+------------------+----------------------+------------------+
| 31|      31|            35.143|              12.5|              6.69|              5.32|                 28.11|              5.35|
| 28|      28|            46.052|             14.52|              7.27|              7.26|                 31.72|               6.6|
| 26|      26|            47.262|             14.86|              7.22|              7.43|                  31.8|               6.7|
| 27|     135|           135.594|             37.57|29.119999999999997|17.799999999999997|                183.97|             16.42|
| 44|      44|            70.327|             17.91|              9.63|               9.5|                 39.27|              9.21|
| 12|     156|           950.988|229.14999999999998|107.81000000000002|111.92000000000002|                557.66|102.41000000000001|
| 22|     132|           273.761| 78.19999999999999|             38.15| 37.11999999999999|                251.05|31.729999999999997|
| 13|     117|           671.405|157.77999999999997|             74.69|              78.5|                404.62| 69.21000000000001|
|  6|      48|           736.793|214.33999999999997| 70.94999999999999|              92.8|    294.42999999999995|             75.19|
| 16|      96|           386.692|             98.57|             48.43|              47.8|                256.47|             41.89|
| 20|     100|           285.078| 76.74000000000001|37.690000000000005|38.370000000000005|                190.47|             32.79|
| 40|      40|              28.0|              11.5|              6.74|               4.0|                 24.35|               3.8|
| 48|      48|             22.08|              8.26|              5.78|              4.25|                 26.73|               3.5|
|  5|      25|             616.5|            161.21|50.739999999999995|             66.95|                185.37|             53.63|
| 19|      76|159.41800000000003|              39.1|26.020000000000003|19.490000000000002|    191.60999999999999|             19.15|
| 15|     120|           547.261|            142.13|             66.07|             68.82|                317.32|             66.55|
| 17|     119|           524.187|            138.04| 59.42999999999999|              67.5|                 268.3| 56.63000000000001|
|  9|      90|           960.648|            240.79| 92.39000000000001|            118.79|    398.12999999999994|103.11999999999998|
|  4|       4|             220.0|              54.0|             11.82|              27.0|                 40.74|              21.0|
|  8|      24|           278.499|             71.68|             27.72|             35.84|                117.28|              31.6|
+---+--------+------------------+------------------+------------------+------------------+----------------------+------------------+
only showing top 20 rows

In [66]:
#groupby 
df_cruise.groupBy('passenger_density').sum().show()

+-----------------+--------+-----------------+---------------+------------------+-----------+----------------------+-----------------+
|passenger_density|sum(Age)|     sum(Tonnage)|sum(passengers)|       sum(length)|sum(cabins)|sum(passenger_density)|        sum(crew)|
+-----------------+--------+-----------------+---------------+------------------+-----------+----------------------+-----------------+
|            71.43|      12|             50.0|            7.0|              7.09|       3.54|                 71.43|             4.45|
|            29.47|       6|            112.0|           38.0|              9.51|       15.0|                 29.47|             10.9|
|            37.42|      30|            233.2|          62.32|25.979999999999997|      31.23|                112.26|             26.6|
|            39.18|      14|             76.8|           19.6|              8.79|       9.67|                 39.18|             12.0|
|            24.78|      12|            2.329|           0.94|              2.96|       0.45|                 24.78|              0.6|
|            44.03|       5|            160.0|          36.34|             11.12|      18.17|                 44.03|             13.6|
|            26.95|      21|           73.941|          27.44|               8.8|      11.75|                 26.95|             8.22|
|            47.62|      15|           83.338|           17.5|              9.64|       8.75|                 47.62|             9.45|
|            29.04|      41|           101.52|          34.96|             15.08|      17.48|                 58.08|            12.28|
|            56.76|      38|             33.6|           5.92|             10.28|       2.96|                113.52|             4.07|
|            38.52|      15|75.33800000000001|          19.56|              8.79|       9.83|                 38.52|             13.0|
|            42.26|      18|            226.0|          53.48|             19.02|      26.74|                 84.52|            24.76|
|            25.66|      25|           73.192|          28.52|               8.8|      11.38|                 25.66|             8.08|
|            40.49|      11|             86.0|          21.24|              9.63|      10.62|                 40.49|              9.3|
|            36.81|      27|          203.018|          55.16|             17.86|       27.0|                 73.62|             21.5|
|            36.02|      42|           360.36|         100.04|             38.48|      42.44|                144.08|            34.43|
|            48.08|      72|             30.0|           6.24|13.200000000000001|       3.12|                144.24|4.800000000000001|
|            41.85|      15|          108.806|           26.0|              9.51|       13.0|                 41.85|             11.1|
|            32.22|      23|             25.0|           7.76|              6.22|       3.86|                 32.22|             3.85|
|             40.5|      13|           85.619|          21.14|              9.57|      10.56|                  40.5|              9.2|
+-----------------+--------+-----------------+---------------+------------------+-----------+----------------------+-----------------+
only showing top 20 rows

In [67]:
df_cruise.groupBy('passenger_density').mean().show()

+-----------------+--------+-----------------+------------------+-----------------+-----------+----------------------+------------------+
|passenger_density|avg(Age)|     avg(Tonnage)|   avg(passengers)|      avg(length)|avg(cabins)|avg(passenger_density)|         avg(crew)|
+-----------------+--------+-----------------+------------------+-----------------+-----------+----------------------+------------------+
|            71.43|    12.0|             50.0|               7.0|             7.09|       3.54|                 71.43|              4.45|
|            29.47|     6.0|            112.0|              38.0|             9.51|       15.0|                 29.47|              10.9|
|            37.42|    10.0|77.73333333333333|20.773333333333333|8.659999999999998|      10.41|                 37.42| 8.866666666666667|
|            39.18|    14.0|             76.8|              19.6|             8.79|       9.67|                 39.18|              12.0|
|            24.78|    12.0|            2.329|              0.94|             2.96|       0.45|                 24.78|               0.6|
|            44.03|     5.0|            160.0|             36.34|            11.12|      18.17|                 44.03|              13.6|
|            26.95|    21.0|           73.941|             27.44|              8.8|      11.75|                 26.95|              8.22|
|            47.62|    15.0|           83.338|              17.5|             9.64|       8.75|                 47.62|              9.45|
|            29.04|    20.5|            50.76|             17.48|             7.54|       8.74|                 29.04|              6.14|
|            56.76|    19.0|             16.8|              2.96|             5.14|       1.48|                 56.76|             2.035|
|            38.52|    15.0|75.33800000000001|             19.56|             8.79|       9.83|                 38.52|              13.0|
|            42.26|     9.0|            113.0|             26.74|             9.51|      13.37|                 42.26|             12.38|
|            25.66|    25.0|           73.192|             28.52|              8.8|      11.38|                 25.66|              8.08|
|            40.49|    11.0|             86.0|             21.24|             9.63|      10.62|                 40.49|               9.3|
|            36.81|    13.5|          101.509|             27.58|             8.93|       13.5|                 36.81|             10.75|
|            36.02|    10.5|            90.09|             25.01|             9.62|      10.61|                 36.02|            8.6075|
|            48.08|    24.0|             10.0|              2.08|              4.4|       1.04|    48.080000000000005|1.6000000000000003|
|            41.85|    15.0|          108.806|              26.0|             9.51|       13.0|                 41.85|              11.1|
|            32.22|    23.0|             25.0|              7.76|             6.22|       3.86|                 32.22|              3.85|
|             40.5|    13.0|           85.619|             21.14|             9.57|      10.56|                  40.5|               9.2|
+-----------------+--------+-----------------+------------------+-----------------+-----------+----------------------+------------------+
only showing top 20 rows

In [70]:
#Dataframe API
#Vector assembler is grouping features together 
# [Age, Tonnage] ----> new feature ---> independent feature
from pyspark.ml.feature import VectorAssembler
featureassembler=VectorAssembler(inputCols=['Age',
               'Tonnage',
               'passengers',
               'length',
               'cabins',
               'passenger_density',
               'crew'],outputCol="Independent feature")

In [71]:
output=featureassembler.transform(df_cruise)

In [72]:
output.show()

+-----------+-----------+---+------------------+----------+------+------+-----------------+----+--------------------+
|  Ship_name|Cruise_line|Age|           Tonnage|passengers|length|cabins|passenger_density|crew| Independent feature|
+-----------+-----------+---+------------------+----------+------+------+-----------------+----+--------------------+
|    Journey|    Azamara|  6|30.276999999999997|      6.94|  5.94|  3.55|            42.64|3.55|[6.0,30.276999999...|
|      Quest|    Azamara|  6|30.276999999999997|      6.94|  5.94|  3.55|            42.64|3.55|[6.0,30.276999999...|
|Celebration|   Carnival| 26|            47.262|     14.86|  7.22|  7.43|             31.8| 6.7|[26.0,47.262,14.8...|
|   Conquest|   Carnival| 11|             110.0|     29.74|  9.53| 14.88|            36.99|19.1|[11.0,110.0,29.74...|
|    Destiny|   Carnival| 17|           101.353|     26.42|  8.92| 13.21|            38.36|10.0|[17.0,101.353,26....|
|    Ecstasy|   Carnival| 22|            70.367|     20.52|  8.55|  10.2|            34.29| 9.2|[22.0,70.367,20.5...|
|    Elation|   Carnival| 15|            70.367|     20.52|  8.55|  10.2|            34.29| 9.2|[15.0,70.367,20.5...|
|    Fantasy|   Carnival| 23|            70.367|     20.56|  8.55| 10.22|            34.23| 9.2|[23.0,70.367,20.5...|
|Fascination|   Carnival| 19|            70.367|     20.52|  8.55|  10.2|            34.29| 9.2|[19.0,70.367,20.5...|
|    Freedom|   Carnival|  6|110.23899999999999|      37.0|  9.51| 14.87|            29.79|11.5|[6.0,110.23899999...|
|      Glory|   Carnival| 10|             110.0|     29.74|  9.51| 14.87|            36.99|11.6|[10.0,110.0,29.74...|
|    Holiday|   Carnival| 28|            46.052|     14.52|  7.27|  7.26|            31.72| 6.6|[28.0,46.052,14.5...|
|Imagination|   Carnival| 18|            70.367|     20.52|  8.55|  10.2|            34.29| 9.2|[18.0,70.367,20.5...|
|Inspiration|   Carnival| 17|            70.367|     20.52|  8.55|  10.2|            34.29| 9.2|[17.0,70.367,20.5...|
|     Legend|   Carnival| 11|              86.0|     21.24|  9.63| 10.62|            40.49| 9.3|[11.0,86.0,21.24,...|
|   Liberty*|   Carnival|  8|             110.0|     29.74|  9.51| 14.87|            36.99|11.6|[8.0,110.0,29.74,...|
|    Miracle|   Carnival|  9|              88.5|     21.24|  9.63| 10.62|            41.67|10.3|[9.0,88.5,21.24,9...|
|   Paradise|   Carnival| 15|            70.367|     20.52|  8.55|  10.2|            34.29| 9.2|[15.0,70.367,20.5...|
|      Pride|   Carnival| 12|              88.5|     21.24|  9.63| 11.62|            41.67| 9.3|[12.0,88.5,21.24,...|
|  Sensation|   Carnival| 20|            70.367|     20.52|  8.55|  10.2|            34.29| 9.2|[20.0,70.367,20.5...|
+-----------+-----------+---+------------------+----------+------+------+-----------------+----+--------------------+
only showing top 20 rows

In [73]:
finalized_data=output.select("Independent feature","passengers")

In [74]:
finalized_data.show()

+--------------------+----------+
| Independent feature|passengers|
+--------------------+----------+
|[6.0,30.276999999...|      6.94|
|[6.0,30.276999999...|      6.94|
|[26.0,47.262,14.8...|     14.86|
|[11.0,110.0,29.74...|     29.74|
|[17.0,101.353,26....|     26.42|
|[22.0,70.367,20.5...|     20.52|
|[15.0,70.367,20.5...|     20.52|
|[23.0,70.367,20.5...|     20.56|
|[19.0,70.367,20.5...|     20.52|
|[6.0,110.23899999...|      37.0|
|[10.0,110.0,29.74...|     29.74|
|[28.0,46.052,14.5...|     14.52|
|[18.0,70.367,20.5...|     20.52|
|[17.0,70.367,20.5...|     20.52|
|[11.0,86.0,21.24,...|     21.24|
|[8.0,110.0,29.74,...|     29.74|
|[9.0,88.5,21.24,9...|     21.24|
|[15.0,70.367,20.5...|     20.52|
|[12.0,88.5,21.24,...|     21.24|
|[20.0,70.367,20.5...|     20.52|
+--------------------+----------+
only showing top 20 rows

In [75]:
from pyspark.ml.regression import LinearRegression
train_data,test_data=finalized_data.randomSplit([0.75,0.25])
regressor=LinearRegression(featuresCol="Independent feature", labelCol="passengers")
regressor=regressor.fit(train_data)

24/11/15 10:04:43 WARN Instrumentation: [b3c2dd73] regParam is zero, which might cause numerical instability and overfitting.

In [76]:
##Coefficients
regressor.coefficients

DenseVector([-0.0, 0.0, 1.0, -0.0, -0.0, -0.0, 0.0])

In [77]:
#Intercepts
regressor.intercept

1.6710689226197786e-12

In [78]:
#Prediction
pred_results=regressor.evaluate(test_data)

In [79]:
pred_results.predictions.show()

+--------------------+----------+------------------+
| Independent feature|passengers|        prediction|
+--------------------+----------+------------------+
|[6.0,30.276999999...|      6.94| 6.940000000000124|
|[6.0,110.23899999...|      37.0|36.999999999999886|
|[7.0,158.0,43.7,1...|      43.7| 43.70000000000006|
|[8.0,77.499,19.5,...|      19.5| 19.50000000000002|
|[8.0,91.0,22.44,9...|     22.44|22.439999999999966|
|[9.0,85.0,19.68,9...|     19.68|19.679999999999936|
|[9.0,105.0,27.2,8...|      27.2|27.200000000000074|
|[10.0,90.09,25.01...|     25.01|25.009999999999913|
|[10.0,151.4,26.2,...|      26.2|26.200000000000433|
|[11.0,90.09,25.01...|     25.01|25.009999999999906|
|[11.0,91.0,20.32,...|     20.32|20.320000000000007|
|[12.0,25.0,3.88,5...|      3.88|  3.87999999999979|
|[12.0,88.5,21.24,...|     21.24|21.239999999999945|
|[12.0,108.865,27....|     27.58|27.580000000000055|
|[12.0,138.0,31.14...|     31.14| 31.14000000000015|
|[13.0,30.27699999...|      6.84| 6.840000000000112|
|[13.0,61.0,13.8,7...|      13.8|13.800000000000002|
|[13.0,85.619,21.1...|     21.14| 21.13999999999988|
|[13.0,91.0,20.32,...|     20.32|20.320000000000004|
|[14.0,77.104,20.0...|     20.02|20.019999999999957|
+--------------------+----------+------------------+
only showing top 20 rows

In [80]:
print(f"""
Linear Regression Results Report
==================================
RMSE:\t {pred_results.rootMeanSquaredError}
MSE:\t {pred_results.meanSquaredError}
R2:\t {pred_results.r2}
Adj R2:\t{pred_results.r2adj}
==================================
"""
)

Linear Regression Results Report
==================================
RMSE:	 1.3343547559699532e-13
MSE:	 1.7805026147796332e-26
R2:	 1.0
Adj R2:	1.0
==================================